"""initial_schema_from_sql_files

Revision ID: 24640762d76f
Revises: 
Create Date: 2026-06-01 18:53:58.431115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24640762d76f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('instituicao', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Course_id'), 'Course', ['id'], unique=False)
    op.create_table('Subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('ementa', sa.Text(), nullable=True),
    sa.Column('bibliografia', sa.Text(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('periodo_recomendado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Subject_id'), 'Subject', ['id'], unique=False)
    op.create_table('CourseSubjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['Subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'subject_id', name='uq_course_subject')
    )
    op.create_index(op.f('ix_CourseSubjects_id'), 'CourseSubjects', ['id'], unique=False)
    op.create_table('Prerequisite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_subject_id'], ['Subject.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['Subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'prerequisite_subject_id', name='uq_prerequisite')
    )
    op.create_index(op.f('ix_Prerequisite_id'), 'Prerequisite', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['Course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('FlowchartItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'completed'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['Subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject_id', name='uq_user_subject')
    )
    op.create_index(op.f('ix_FlowchartItem_id'), 'FlowchartItem', ['id'], unique=False)
    op.create_table('Review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('resenha', sa.Text(), nullable=True),
    sa.Column('comprovante_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['Subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Review_id'), 'Review', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Review_id'), table_name='Review')
    op.drop_table('Review')
    op.drop_index(op.f('ix_FlowchartItem_id'), table_name='FlowchartItem')
    op.drop_table('FlowchartItem')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Prerequisite_id'), table_name='Prerequisite')
    op.drop_table('Prerequisite')
    op.drop_index(op.f('ix_CourseSubjects_id'), table_name='CourseSubjects')
    op.drop_table('CourseSubjects')
    op.drop_index(op.f('ix_Subject_id'), table_name='Subject')
    op.drop_table('Subject')
    op.drop_index(op.f('ix_Course_id'), table_name='Course')
    op.drop_table('Course')
    # ### end Alembic commands ###
