"""create subjects and prerequisites tables

Revision ID: 3a8768475f9e
Revises: b3ce0799c916
Create Date: 2026-05-27 09:33:54.956867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8768475f9e'
down_revision: Union[str, None] = 'b3ce0799c916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('ementa', sa.Text(), nullable=True),
    sa.Column('bibliografia', sa.Text(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('periodo_recomendado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prerequisites_id'), 'prerequisites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prerequisites_id'), table_name='prerequisites')
    op.drop_table('prerequisites')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
